### ISSUE TITLE
Infografía: Gestión de proyectos de software

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Ferch0419#2]
[GESTIÓN DE PROYECTOS DE SOFTWARE_Fernando Miguel López.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Ferch0419/files/9420324/GESTION.DE.PROYECTOS.DE.SOFTWARE_Fernando.Miguel.Lopez.pdf)

**Comment by bg55-a** [comment]
Calificación 20%

**Comment by Brisa-4** [comment]
Calificación: 20/20
